export const CURRENCY = "currency";
export const CATEGORY = "category";
export const ALLCATEGORY = "allCategory";
export const ALLCURRENCY = "allCurrencies";
export const CARTMINI = "cartMini";
// export const CURRENCY = "currency";
// export const CURRENCY = "currency";
// export const CURRENCY = "currency";
// export const CURRENCY = "currency";
